language: node_js
cache: 'npm'
os: 'osx'
node_js: '12'
install:
  - npm ci
  - npm install -g codecov c8
script:
  - npm run build
  - c8 npm test
  - c8 report --reporter=text-lcov > coverage.lcov
  - codecov
  - nvm install 10
  - sleep 3
  - npm run test
  - nvm install 8
  - sleep 3
  - npm run test
