language: node_js
node_js:
- '12'
# - '10'
# - '8'
install:
- npm install
script:
- echo 'test'
# - npm run test
# - npm run lint
# after_success:
# - npm install -g codecov
# - tap --coverage-report=text-lcov > coverage.lcov
# - codecov
