language: node_js
cache:
  directories:
    - $HOME/.npm
    - node_modules
os:
  # - linux
  - osx
  # - windows
node_js:
  - '12'
  # - '10'
install:
  - npm install
script:
  - npm run build
  - npm test
# after_success:
#   - npm install -g codecov
#   - tap --coverage-report=text-lcov > coverage.lcov
#   - codecov
