language: node_js
cache: npm
os: osx
node_js: '12'
addons:
  chrome: stable
install:
  - wget https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - npm ci
  - npm install -g codecov c8
script:
  - npm run build
  - c8 npm run test
  - c8 npm run test-client
  - c8 report --reporter=text-lcov > coverage.lcov
  - codecov
  - nvm install 10
  - npm run test
  - nvm install 8
  - npm run test
