language: node_js
node_js:
- '10'
- '8'
install:
- npm install
script:
- npm run test
- npm run lint
after_success:
- npm install -g codecov
- tap --coverage-report=text-lcov > coverage.lcov
- codecov
