/* eslint-disable */
// This file is generated by esifycss.
import {addStyle} from './helper.js';
addStyle(["YaIcGyCCOQCeAOEgBQCeAWEE","YaIiBG0CCOQCkBASmBIIOoBqBEgBQCkBASmB4BoBqBEE","6B8BGOC+BAgCUMAiCsBIuBIcGyCE","wByBGWCMKkCAWsBUMKmCKoCAqCUMKsCKuCAuBE","wByBG+CSGgDCMKwCAiBG0CE"]);
export const className = {
    "icon": "icon_1",
    "rotate": "rotate_2"
};
export const id = {
    "container": "container_0"
};
export const keyframes = {
    "FadeIn": "FadeIn_3",
    "Rotate": "Rotate_4"
};
