/* eslint-disable */
// This file is generated by esifycss.
import {addStyle} from './helper.js';
addStyle(["YaIcGyCCOQCeAOEgBQCeAWEE","YaIiBG0CCOQCkBASmBIIOoBqBEgBQCkBASmB4BoBqBEE","6B8BG6CC+BAgCUMAiCsBIuBIcGyCE","wByBG8CCMKkCAWsBUMKmCKoCAqCUMKsCKuCAuBE","wByBG+CSGgDCMKwCAiBG0CE"]);
export const className = {
    "icon": "icon_6",
    "rotate": "rotate_7"
};
export const id = {
    "container": "container_5"
};
export const keyframes = {
    "FadeIn": "FadeIn_8",
    "Rotate": "Rotate_9"
};
