// SPDX-License-Identifier: Apache-2.0
const fs = require('fs');
const path = require('path');

const source = path.resolve(__dirname, '../src');
const output = path.join(source, 'index.ts');
const files = [];
const collect = (directory) => {
    for (const name of fs.readdirSync(directory).sort()) {
        const file = path.join(directory, name);
        if (fs.statSync(file).isDirectory()) {
            if (name !== 'bin' && name !== 'helper') collect(file);
        } else if (file !== output && name.endsWith('.ts') && !/\.(test|d)\./.test(name)) {
            files.push(file);
        }
    }
};
collect(source);
if (!files.length) throw new Error('No source files found; leaving index.ts intact.');
const code = [
    '// Generated by scripts/generate-index.js',
    ...files.sort().map((file) => {
        const relative = './' + path.relative(source, file).split(path.sep).join('/').slice(0, -3);
        return `export * from '${relative.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}';`;
    }),
    '',
].join('\n');
fs.writeFileSync(output, code);
