/* eslint-disable */
// This file is generated by esifycss.
import {addStyle} from './helper.js';
addStyle(["WYIGuBCOQCaAOEcQCaAUEE","WYIGwBCOQCeAgBiBIIOkBmBEcQCeAgBiByBkBmBEE","0BGOC2BA4BSMA6BoBIqBIGuBE","sBGUCMK8BAUoBSMK+BKgCAiCSMKkCKmCAqBE","sBGuCGwCCMKoCAGwBE"]);
export const className = {
    "icon": "_1",
    "rotate": "_2"
};
export const id = {
    "container": "_0"
};
export const keyframes = {
    "FadeIn": "_3",
    "Rotate": "_4"
};
